### ISSUE TITLE
没有使用rx的项目直接使用PuckRxJavaRunner出现NoClassDefFoundError

### ISSUE THREAD

**Issue by znyang** [znyang/puck#4]
```
java.lang.NoClassDefFoundError: rx/plugins/RxJavaSchedulersHook

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.robolectric.RobolectricTestRunner.assureTestLifecycle(RobolectricTestRunner.java:76)
	at org.robolectric.RobolectricTestRunner.access$600(RobolectricTestRunner.java:47)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:221)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
```

**Comment by znyang** [comment]
添加兼容实现
